### ISSUE TITLE
Permitir upload de outros arquivos que não pdf (jpeg, png)

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/bibfiles#15]

**Comment by isabelakashima** [comment]
Testado, é possível adicionar pdf e jpg.
O bmp também foi testado, mas não permitiu o upload.

**Comment by thiagogomesverissimo** [comment]
- Trocar o ícone do pdf para outro ícone quando não pdf
- Verificar se a extensão está correta para arquivos não pdf
- testar com mp3 e mp4
